### PR TITLE
Re-Enable CI-Infra Terraform checks

### PR DESCRIPTION
**Pull request by joeyg**
## Ticket

No ticket that I'm aware of.

## Changes

* Re-enable CI-Infra checks
* Fix some spacing issues

## Context for reviewers

* ~~There is a [failing check in terraform](https://github.com/joeyg/iv-cbv-payroll/actions/runs/10173629424/job/28138022832)~~
* ~~This is blocked by #120.~~

## Testing

* Running the checks here: https://github.com/joeyg/iv-cbv-payroll/pull/4/checks

### CODE REVIEW

**Comment by joeyg** [comment]
@GeorgeCodes19 Do you mind looking at this terraform check failure https://github.com/joeyg/iv-cbv-payroll/actions/runs/10173629424/job/28138022832 ?

**Comment by tdooner** [comment]
@joeyg I say we ignore that check. We needed to make that IAM user for the Massachusetts integration.

**Comment by joeyg** [comment]
@tdooner thanks. I updated the PR to [skip that check](https://github.com/joeyg/iv-cbv-payroll/actions/runs/10188737627/job/28185454094?pr=4). I'll move this to review once #120 lands.

**Comment by joeyg** [comment]
@tdooner @allthesignals @GeorgeCodes19 for your review

**Review by tdooner — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
