### PR TITLE
Fix employer search fallback to show up with exactly 1 result

### PR DESCRIPTION
**Pull request by tdooner**
## Ticket

Resolves FFS-1438.

## Changes

Oops, an off-by-1 error!

## Context for reviewers

N/A

## Testing

Tested locally, it works.

### CODE REVIEW

**Comment by tdooner** [comment]
@carmenrosalop 
image

**Review by carmenrosalop — APPROVED** [review]
Excellent! Thanks Tom!

**Review by acouch — APPROVED** [review]

**Comment by tdooner** [comment]
> Update: I realized that the Employer not listed text should be H2, same as the Results heading @tdooner

@carmenrosalop Fixed
image

**Comment by carmenrosalop** [comment]
Thanks Tom!

**Pull request merged**
