### PR TITLE
OWASP runner

### PR DESCRIPTION
**Pull request by joeyg**
## Ticket

Resolves [FFS-1083](https://jiraent.cms.gov/browse/FFS-1083)

## Changes

Make the OWASP running actually run.

## Context for reviewers
[Link](https://github.com/joeyg/iv-cbv-payroll/actions/runs/10120352661/job/27989999390)

There are a few failures. Not sure what the team would like to do about those:
```WARN-NEW: CSP: Notices [10055] x 6 
	http://localhost:3000/ (200 OK)
	http://localhost:3000/ (200 OK)
	http://localhost:3000/ (200 OK)
	http://localhost:3000/cbv/agreement (200 OK)
	http://localhost:3000/cbv/entry (200 OK)
WARN-NEW: Permissions Policy Header Not Set [10063] x 4 
	http://localhost:3000/ (200 OK)
	http://localhost:3000/cbv/agreement (200 OK)
	http://localhost:3000/cbv/entry (200 OK)
	http://localhost:3000/assets/application-5b1daa56fc52f867eb19dfecd7e4e06be4255b795514de338a8bdaebc71a9730.js (200 OK)
WARN-NEW: Dangerous JS Functions [10110] x 1 
	http://localhost:3000/assets/application-5b1daa56fc52f867eb19dfecd7e4e06be4255b795514de338a8bdaebc71a9730.js (200 OK)
FAIL-NEW: 0	FAIL-INPROG: 0	WARN-NEW: 3	WARN-INPROG: 0	INFO: 0	IGNORE: 0	PASS: 131
```

### CODE REVIEW

**Comment by joeyg** [comment]
@tdooner I moved the PR to this one on my @joeyg account. The tests do run now but have the errors noted in the PR description.

**Comment by acouch** [comment]
Great progress. Do you have instructions for running locally? Starting off w/ `docker run -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://localhost:3000` isn't working. I've not run this locally before, so digging into the zap docks.

**Comment by joeyg** [comment]
@acouch Thanks for taking a look. I was able to run it locally by doing this:
```
docker pull ghcr.io/zaproxy/zaproxy:stable
docker run -v $(pwd):/zap/wrk/:rw --network=host -e ZAP_AUTH_HEADER -e ZAP_AUTH_HEADER_VALUE -e ZAP_AUTH_HEADER_SITE -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://localhost:3000/ -J report_json.json -w report_md.md -r report_html.html -T 1 -c app/zap.conf -I -z "-configfile /zap/wrk/zap/zap_options.conf"
```

**Comment by acouch** [comment]
@joeyg when I run that on my Mac M2 I get: 

```
(app)(main)$docker run -v $(pwd):/zap/wrk/:rw --network=host -e ZAP_AUTH_HEADER -e ZAP_AUTH_HEADER_VALUE -e ZAP_AUTH_HEADER_SITE -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://localhost:3000/ -J report_json.json -w report_md.md -r report_html.html -T 1 -c app/zap.conf -I -z "-configfile /zap/wrk/zap/zap_options.conf"
Traceback (most recent call last):
  File "/zap/zap-full-scan.py", line 529, in <module>
    main(sys.argv[1:])
  File "/zap/zap-full-scan.py", line 254, in main
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/zap/wrk/app/zap.conf'
```

**Comment by acouch** [comment]
Reviewing the list above: 

> WARN-NEW: Dangerous JS Functions [10110] x 1 
	http://localhost:3000/assets/application-5b1daa56fc52f867eb19dfecd7e4e06be4255b795514de338a8bdaebc71a9730.js (200 OK)

This one is LOW. One of the commands from the js bundle executes `eval()` somewhere down the tree. Similar to: https://github.com/zaproxy/zaproxy/issues/7732 Would take some time to find. Would recommend ignoring.

> WARN-NEW: Permissions Policy Header Not Set [10063] x 4 

This is also a LOW. A small config update would fix. 

> WARN-NEW: CSP: Notices [10055] x 6

This is MEDIUM. 
image

There are a couple of fixes here: 

- [ ] `script-src includes unsafe-inline.`
- [ ] `style-src includes unsafe-inline.`
- [ ] `Errors: Unrecognised nonce 'nonce-'`

**Comment by acouch** [comment]
I'm not sure how to contribute to a remote branch w/o contributing directly to the remote repo so started: https://github.com/DSACMS/iv-cbv-payroll/pull/122

**Comment by tdooner** [comment]
Closing in favor of #122. Thanks for your help on it @joeyg .

**Pull request closed without merging**
