### PR TITLE
Make "90 days" and "gross income" more prominent

### PR DESCRIPTION
**Pull request by tdooner**
## Ticket

Resolves FFS-1406.

## Changes

Copy changes on payment details and summary pages.

## Context for reviewers

N/A

## Testing

Acceptance testing by Carmen.

### CODE REVIEW

**Comment by tdooner** [comment]
@carmenrosalop For your acceptance testing:

Payment details page:
image

Summary page:
image

**Review by carmenrosalop — CHANGES_REQUESTED** [review]
The payment details page looks great! 
For the summary page, I don't see the update of the 90 days on the H2

**Review by carmenrosalop — APPROVED** [review]
Not sure why but now I see both pages updated. Looks good!

**Comment by tdooner** [comment]
Ah maybe it was because I edited my comment a couple times.

**Pull request merged**
