### PR TITLE
Add help text for caseworker invite fields

### PR DESCRIPTION
**Pull request by tdooner**
## Ticket

N/A - I did this since I keep forgetting the format of these fields, and
figured that caseworkers may appreciate the hint as well.

## Changes

Since we validate the format of these fields, let's provide a visual
hint of the correct format as the field's help text.

**NYC:**
image

**MA:**
image

## Context for reviewers

N/A

## Testing

N/A

### CODE REVIEW

**Comment by tdooner** [comment]
@carmenrosalop What do you think about adding placeholders to the caseworker fields that have format validation? (See screenshots above)

**Comment by tdooner** [comment]
@carmenrosalop Updated! New screenshots in the original message above ^

**Review by carmenrosalop — APPROVED** [review]
Looks great! Thanks Tom!

**Review by GeorgeCodes19 — APPROVED** [review]
Makes sense to me.

**Pull request merged**
