### PR TITLE
Implement caseworker /dashboard page

### PR DESCRIPTION
**Pull request by tdooner**
## Ticket

Resolves FFS-1299.

## Changes

* Create a new page after the SSO but before the
  /:site_id/invitations/new page.
* This page has some basic instructions for caseworkers, and a link to
  the invitations screen.

## Context for reviewers

N/A

## Testing

Tested locally. Will acceptance test with Carmen.

### CODE REVIEW

**Comment by tdooner** [comment]
@carmenrosalop Tagging you for acceptance testing.

This is the screenshot after logging in:
image

Screenshot after sending an invitation:
image

**Review by carmenrosalop — CHANGES_REQUESTED** [review]
Thanks Tom! Looks good.
Can we update blue banner (that confirms being signed in) to slim? And remove the word "Information" and say "You are signed in."
Screenshot 2024-08-19 at 1 27 09 PM

**Comment by tdooner** [comment]
@carmenrosalop You bet. Updated screenshot:
image

**Review by carmenrosalop — APPROVED** [review]
Thanks Tom! LGTM!

**Review by GeorgeCodes19 — APPROVED** [review]

**Pull request merged**
