### PR TITLE
Implement designs for /cbv/success page

### PR DESCRIPTION
**Pull request by tdooner**
## Ticket

Resolves FFS-1237.

## Changes

Adds a redesigned /cbv/success page.

## Context for reviewers

N/A

## Testing

Tested locally.

### CODE REVIEW

**Comment by tdooner** [comment]
@carmenrosalop Here is the implemented design for the /cbv/success page.
image

The header length is kind of long, but I'm not sure what to do about it. Whatever we do, it should probably be across-the-board. If you have thoughts on that, I could work it into my other PR with the across-the-board style changes. Should I just make the headers max out at 8-out-of-12 columns wide or something?

**Review by carmenrosalop — CHANGES_REQUESTED** [review]
Thanks Tom! You're right that the length of the H1 is too long. I'm wondering if updating the "measure" can help with making the length of the H1 match the updated length of the body https://designsystem.digital.gov/design-tokens/typesetting/measure/
Also, you might have already done this, but we need to remove this banner when users get to this success page since they already are getting the confirmation message in the H1. 
Screenshot 2024-08-21 at 6 04 07 PM

**Review by GeorgeCodes19 — APPROVED** [review]

**Comment by tdooner** [comment]
@carmenrosalop Good news - the message was removed by George in #191.

**Review by carmenrosalop — APPROVED** [review]
Approved!

**Pull request merged**
