### PR TITLE
Fix OWASP test

### PR DESCRIPTION
**Pull request by JosephGasiorekUSDS**
## Ticket

Resolves [FFS-1083](https://jiraent.cms.gov/browse/FFS-1083)

## Changes

* Bring OWASP tests back to working.

## Context for reviewers

The [OWASP test have not been running for some time](https://github.com/DSACMS/iv-cbv-payroll/actions/workflows/owasp-daily-scan.yml).

## Testing

> Provide evidence that the code works as expected. Explain what was done for testing and the results of the test plan. Include screenshots, [GIF demos](https://www.cockos.com/licecap/), shell commands or output to help show the changes working as expected. ProTip: you can drag and drop or paste images into this textbox.

### CODE REVIEW

**Comment by joeyg** [comment]
@tdooner Are we able to put Sandbox credentials for pinwheel up on github? This fails because it try's to make requests to pinwheel

**Comment by tdooner** [comment]
@joeyg We could, I guess, as a secret environment variable. Is OWASP going through every page in the app or something? I'm just trying to think about what the right thing to do here is architecturally - do we want to somehow stub out Pinwheel in test environments so we're not actually making 3rd party calls. Certainly the Pinwheel webhooks will not arrive properly without some legwork. Can we just have it exclude the "Start Flow Manually" link on the homepage if it's just crawling for links?

**Comment by joeyg** [comment]
@tdooner you can block URLs but there is a bug preventing that from working https://github.com/zaproxy/action-full-scan/issues/83

**Comment by tdooner** [comment]
@joeyg Hm, that sucks. Can we pass in a `-configfile` with these fields rather than having to pass in these escaped regexes on the command line?

**Comment by tdooner** [comment]
@joeyg What is your capacity going to be to work on this? Do you want to keep taking this PR on or should we take it back?

**Comment by joeyg** [comment]
@tdooner thanks for asking - you all should take it on if you need it done soon. My availability changes a lot from day to day.

**Comment by tdooner** [comment]
Closing in favor of #116

**Pull request closed without merging**
