### PR TITLE
Use NYC-specific copy in applicant invitation email

### PR DESCRIPTION
**Pull request by tdooner**
## Ticket

Resolves FFS-1415

## Changes

Modifies the copy for the body of the invitation email.

## Context for reviewers

N/A

## Testing

Screenshots will be provided for acceptance testing.

### CODE REVIEW

**Comment by tdooner** [comment]
@carmenrosalop For acceptance testing:
NYC email:
image

MA Email:
image

**Review by carmenrosalop — CHANGES_REQUESTED** [review]
The last  line should say "To verify your income with the SNAP Income Pilot..."

**Comment by tdooner** [comment]
@carmenrosalop Ah, didn't notice that had changed. Updated:

NYC:
image

MA:
image

**Review by carmenrosalop — APPROVED** [review]
LGTM!

**Pull request merged**
